name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Get Date
      id: get-date
      run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_ENV

    - name: Cache Buildozer global directory
      uses: actions/cache@v3
      with:
        path: ~/.buildozer
        key: buildozer-global-${{ hashFiles('buildozer.spec') }}

    - name: Build with Buildozer Action
      uses: ArtemSuldin/buildozer-action@v1.2
      with:
        command: buildozer -v android debug
        submodule_update: false

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v3
      with:
        name: TaxSoftware-Android-APK
        path: bin/*.apk
